# Generated by Django 2.0.3 on 2018-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Watch', 'Watch'), ('Sippers', 'Sippers')], max_length=50)),
                ('order_status', models.CharField(default='Submitting details', max_length=50)),
            ],
        ),
    ]
