# Generated by Django 2.0.3 on 2018-06-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180618_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Watch', 'Watch'), ('Sippers', 'Sippers')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('add_value', models.IntegerField(default=0)),
                ('order_status', models.CharField(default='Submitting details', max_length=50)),
                ('item_stock_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='value',
            new_name='add_value',
        ),
        migrations.AddField(
            model_name='buyer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
